### ISSUE TITLE
compareProbabilities method giving repetitive results

### ISSUE THREAD

**Issue by Lorenzo-Martinez** [AlexChido/VallinRomo_CSCI2270_FinalProject#16]
When I pick option 10: "Compare Odds" multiple times in a row, it gives the same result every time, even with a wide range of numbers. For example, if I input 3, 50 and 70 for option 10, it always says "That is approximately the same chance of bowling a perfect 300 game."

**Comment by lamc8684** [comment]
Is this with the Tree.cpp from this repo? The one in my repo may be an older version. When I run the file in CodeBlocks I get this:
![function10](https://cloud.githubusercontent.com/assets/10779384/7404160/7010a0b8-ee9c-11e4-81b9-b91c0b230af6.JPG)
And everything has already been committed and pushed. 
Let me know if updating the file fixes it. Thank you!

**Comment by lamc8684** [comment]
I just fixed the error when entering "3" and having two probabilities show, as well

**Comment by Lorenzo-Martinez** [comment]
I'll try updating it and testing it again.

**Comment by Lorenzo-Martinez** [comment]
![image](https://cloud.githubusercontent.com/assets/10778136/7404360/9678fb40-ee9e-11e4-8283-d52007719345.png)

I'm still getting it, albeit not in the same way as before.
(P.S. The image is a bit big, so click on it to see a better resolution)

**Comment by lamc8684** [comment]
It's possible you may have updated before I could submit the fix. Hopefully if you pull it one more time, it will be fixed

**Comment by Lorenzo-Martinez** [comment]
It only repeats the marriage one with numbers 3 and 90 now.

**Comment by lamc8684** [comment]
![compare](https://cloud.githubusercontent.com/assets/10779384/7404713/87217630-eea4-11e4-82c0-8ff7d99276df.JPG)
it seems fixed in the most recent update to that file. Also it should be printing it out for 90. We don't have that many probabilities stored for bigger percentages so anything from 70-100 will print that one out

**Comment by Lorenzo-Martinez** [comment]
Ok, it seems to be fixed. I'll close the issue.
